language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
  - osx
  
# Select compatible Smalltalk image(s)
smalltalk:
  - Squeak64-trunk
  - Squeak64-5.3
  - Squeak64-5.2
  - Squeak32-trunk
  - Squeak32-5.3
  - Squeak32-5.2
  - Squeak32-5.1
  
matrix:
  allow_failures:
    - smalltalk: Squeak-5.0
  fast_finish: true
